### ISSUE TITLE
Python=3.11 support

### ISSUE THREAD

**Issue by valeriupredoi** [conda-forge/basemap-feedstock#109]
I am aware this might be a stretch, but are people planning a Python=3.11-supported version? Cheers muchly in advance :beer:

**Comment by molinav** [comment]
Hi, @valeriupredoi! Technically, `basemap` upstream already supports Python 3.11, so it should not be a big deal if `conda` already has support for Python 3.11.

I would need to get the automatic recipe files updated and not much more. Normally, some bot is opening a pull request when this is possible, but I guess that I can also force a conda-recipe update automatically. Just let me find some free time. ;-)

**Comment by valeriupredoi** [comment]
very cool, cheers @molinav :beer: Take your time, no hurry from my side - let me know if I can help in any way! I had a look at the meta.yml and indeed, it looks like python is not pinned there, so a bump build number/re-build will probably do it methinks :+1:

**Comment by molinav** [comment]
@conda-forge-admin, please rerender

**Comment by molinav** [comment]
@valeriupredoi The `conda` packages for Python 3.11 are now available in `conda-forge` for GNU/Linux x64, Windows x64 and MacOS x64. It would be great if you can provide feedback about these packages working properly in your workflows.

**Comment by valeriupredoi** [comment]
@molinav you are a legend, very many thanks! Indeed, my conda env now solves nicely with `basemap=1.3.6` and `python=3.11`, see [test](https://github.com/valeriupredoi/bgcval2/actions/runs/4281837903/jobs/7455348448) (don't worry about the fails - those are my bads, the env solves correctly though, for linux64, I've not tested it for MacOS just yet, since I don't support that for that particular package, but will check in the very near future for another of our packages). Cheers muchly! :beer:
