### ISSUE TITLE
[Question] Is there going to be a Python=3.12 build...

### ISSUE THREAD

**Issue by valeriupredoi** [conda-forge/basemap-feedstock#119]
...or you guys are done rebuilding something a bit ye olde for more modern Pythons? :snake: Cheers very much - let me know if I can help in any way :beer:

**Comment by molinav** [comment]
Hi @valeriupredoi! The support for Python 3.12 needs to come first in the upstream repository (https://github.com/matplotlib/basemap), then it should be straightforward here.

I targeted this for the `basemap` release 1.4.0; regarding Python 3.12 the main thing is to remove the remainders of `distutils` (not sure if I already completed it). I just need to find some spare time to take a look on it, probably within a couple of weeks.

**Comment by valeriupredoi** [comment]
@molinav good man! Happy to hear there's still push to keep it afloat and titop Python-ed 🐍 🍺

**Comment by molinav** [comment]
@valeriupredoi The migration to Python 3.12 is completed in the `basemap` upstream repository. I want to make one last change before release 1.4.0 (remove old unicode literal syntax), so I hope to get 1.4.0 ready either today or tomorrow. Then it is only a matter of days that this feedstock gets regenerated, and then we will have support for Python 3.12 in `conda-forge`.

**Comment by molinav** [comment]
@valeriupredoi Packages for Python 3.12 are finally available in the `conda-forge` channel!

**Comment by valeriupredoi** [comment]
@molinav that's mega, great many thanks, mate! Am travelling back from holidays today, but will have a closer look and env test at our end tomorrow, cheers muchly 🍺

**Comment by valeriupredoi** [comment]
brilliant work, I just tested with our env, and basemap is now happily 3.12-ing :beer: :beer:
