### ISSUE TITLE
Getting ready for v1.1.0 upstream release

### ISSUE THREAD

**Issue by WeatherGod** [conda-forge/basemap-feedstock#15]
I am working on getting v1.1.0 of basemap released shortly. One thing I would like to see get fixed with the conda version of basemap (or perhaps upstream, if possible) is the problem of version mismatch for libgeos. While geos-3.5.* is specified for the build of basemap, if the bugfix number for geos gets bumped and the package updated in conda, then import of basemap fails because it tries to import the libgeos_c.so file with the full version number, and can't find it if the geos package version doesn't match.

I am not exactly sure what is the right way to solve this, but I am willing to help.

**Comment by ocefpaf** [comment]
> I am working on getting v1.1.0 of basemap released shortly. 

:+1: 

> One thing I would like to see get fixed with the conda version of basemap (or perhaps upstream, if possible) is the problem of version mismatch for libgeos. While geos-3.5.* is specified for the build of basemap, if the bugfix number for geos gets bumped and the package updated in conda, then import of basemap fails because it tries to import the libgeos_c.so file with the full version number, and can't find it if the geos package version doesn't match.

If a minor update in `geos` breaks ABI them `geos` version is not really semver, but we did use `3.5.0` and `3.5.1` for a long time now without any breakages like the on you described.

Can you share a log/example where that happened? Maybe it was related to a `conda-forge` vs `defaults` issue instead? See the docs we are writing in https://github.com/conda-forge/conda-forge.github.io/pull/325

PS: We do plan to move to `geos 3.6.*` soon but that will require a re-build of many packages.

**Comment by WeatherGod** [comment]
Trying to find an old conda environment where this was happening, but I am not sure if it is a semver issue. The import error that I would get is something along the lines of ".../lib/libgeos_c-3.3.3.so could not be found". So, it is trying to find the 3.3.3 .so instead of trying for the libgeos_c-3.3.so symbolic link. I'll dig some more to see if I can figure out what the exact environment was that caused this.

**Comment by WeatherGod** [comment]
correction... libgeos, not libgeos_c... I think...

**Comment by ocefpaf** [comment]
I guess that, if this happens here, we can patch that file name and issue a new build number quickly. We did not have this problem when using 3.5.0 and 3.5.1.

**Comment by WeatherGod** [comment]
agreed... I am having trouble reproducing it now.
