### ISSUE TITLE
Basemap installs but is not seen by Python

### ISSUE THREAD

**Issue by kalefranz** [conda-forge/basemap-feedstock#22]
_From @fonnesbeck on September 12, 2017 1:5_

Creating a conda env with `basemap` named as one of the packages installs cleanly, but results in the following when basemap is imported:

```
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-db00e19d8b31> in <module>()
----> 1 import basemap

ModuleNotFoundError: No module named 'basemap'
```

I've added `conda-forge` and `anaconda` to the channels list, and have confirmed that basemap is in the `share` subdir in the env.

Conda reports that the package is installed:

```
$ conda install -c conda-forge basemap
Fetching package metadata ...........
Solving package specifications: .

# All requested packages already installed.
# packages in environment at /Users/fonnescj/anaconda3/envs/bios8366:
#
basemap                   1.1.0                    py36_2    conda-forge
```

Running Python 3.6 on macOS 10.12.

_Copied from original issue: conda/conda#5952_

**Comment by ocefpaf** [comment]
> named as one of the packages

Not sure what you mean, is it name after `basemap` or any package in the same `env`?

I just tried,

```shell
conda create --yes --name basemap python=3.6 basemap --channel conda-forge
source activate basemap
python -c "import mpl_toolkits.basemap as basemap; print(basemap.__version__, basemap.__file__)"
1.1.0 /home/filipe/miniconda3/envs/basemap/lib/python3.6/site-packages/mpl_toolkits/basemap/__init__.py
```

**Comment by ocefpaf** [comment]
OK. Just read the original issue and it is a misconception on how to use the module.

See https://github.com/conda/conda/issues/5952#issuecomment-331142370
