### ISSUE TITLE
basemap library updated on GitHub

### ISSUE THREAD

**Issue by scollis** [conda-forge/basemap-feedstock#25]
Hey feedstock maintainers. basemap has been updated with a fix for the way numpy 1.14 handles io. Could you please update so we get the latest in conda-forge?

**Comment by ocefpaf** [comment]
@scollis the latest release is https://github.com/matplotlib/basemap/releases/tag/v1.1.0

I'll try to find the changes and patch it but it would be nice to have a new official release instead.

**Comment by ocefpaf** [comment]
@scollis I could not find the commits to create a patch. Can you point me to those changes?

**Comment by scollis** [comment]
Ping @WeatherGod

**Comment by scollis** [comment]
This is the specific one that motivates my request: https://github.com/matplotlib/basemap/pull/386

Fixed issues with dep. warnings in my unit tests for Py-ART

**Comment by WeatherGod** [comment]
I thought the feedstock just tracks master? Would it be enough if I made tags?

**Comment by ocefpaf** [comment]
> I thought the feedstock just tracks master?

Nope. We only do that in the last case scenario for abandoned projects that won't get a release anytime soon. 

> Would it be enough if I made tags?

Ideally an official release is better but we can use tags. However, I already backported that change and if @scollis is OK with that solution you don't need to worry about a new release for now.
