### ISSUE TITLE
Install basemap in Julia

### ISSUE THREAD

**Issue by GauravDoshi9** [conda-forge/basemap-feedstock#27]
I am trying to update my basemap from conda-forge in Julia since the basemap version in conda is v1.0.7. However, I am not sure how to update basemap from conda-forge in Julia environment. Can someone please help me do this?

**Comment by ocefpaf** [comment]
It is not clear to me what you mean by `Julia` environment. How did you install `Julia`?

This command here is an example of how to start an environment with `conda-forge`'s `basemap` and `Julia`:

```shell
conda create --name JULIA --channel conda-forge basemap basemap-data-hires julia
```

**Comment by GauravDoshi9** [comment]
What I mean is, can I use `conda-forge` as a binary provider for `Julia`?
Let me give an example. If I have to install a `conda` package like `basemap` in `Julia`, i'd do:
```
using Conda
Conda.add("basemap")
```
The `basemap` package in v1.0.7, that is why I want to use `conda-forge`'s basemap.

**Comment by ocefpaf** [comment]
I have no idea of how how  `Conda` works in `Julia` and how the python package will be called there.
Sorry, I cannot help you with that. You are better off asking that in a Julialang forum or stackoverflow.

This feedstock is about the python basemap package for conda.
