### ISSUE TITLE
most recent basemap package for win64+py27 broken?? (1.1.0 build 5)

### ISSUE THREAD

**Issue by megies** [conda-forge/basemap-feedstock#36]
Issue:

The most recent basemap package available through conda-forge for win64+py27 that gets installed by default seems broken (see e.g. [here, breaking our appveyor CI tests in obspy/obspy](https://ci.appveyor.com/project/obspy/obspy/builds/19346925/job/prqqev70hy0qt786#L691)). I think the underlying problem (proj data directory not being found) was already fixed on master but at the same time of the fix the builds for win-64+py27 were deactivated, so no packages including the fix were built for win64. In any case this problems seems to circle around certain combinations of basemap+pyproj+proj4 installed versions.

After some hours of debugging I still don't understand what is getting wrong and why `PROJ_LIB` env var is empty in our CI (untarring the packages that get installed there have it properly in the activation script).

I'll try to monkey patch this in our CI by setting `PROJ_LIB` manually for now, lacking a better solution right now..

**Comment by ocefpaf** [comment]
@megies we are stretched thin and fixing Windows+Python 2.7 is not a priority at the moment. Do you want to send PRs back-porting the fixes?

**Comment by ocefpaf** [comment]
Closing this as a won't fix b/c it would need a rebuild of old `proj.4` that works with `vc9`, than `pyproj`, than `basemap`. I don't have the time for that and the advantages of supporting a deprecated package, on a dying Python version, on Windows is really low at the moment.
