### ISSUE TITLE
How are you creating the env? What are the results of

### ISSUE THREAD

**Issue by jamessong** [conda-forge/basemap-feedstock#39]
```
echo $PROJ_LIB
```

and 

```
echo $CONDA_PREFIX
```

?

Looks to me that you are installing things in the root env where there won't be the env variables activation.

_Originally posted by @ocefpaf in https://github.com/conda-forge/basemap-feedstock/issues/30#issuecomment-418708551_

**Comment by ocefpaf** [comment]
> are you sure you can type these commands in windows 10?

You must adapt that for Windows. After Googling env variables on Windows I got:

```
echo %PROJ_LIB%
```

It seems that you need to wrap it with `%` instead of the leading `$`.
