### ISSUE TITLE
> Now only the remaining question, how we can get the CIs to run build tests in an environment

### ISSUE THREAD

**Issue by jamessong** [conda-forge/basemap-feedstock#40]
I usually do this:

https://github.com/python-visualization/folium/blob/master/.travis.yml#L29-L36

> or how we could add the path to proj_lib.

Your script looks too complex IMO. If you are using conda you can do:

```
set "PROJ_LIB=%CONDA_PREFIX%\Library\share"  # Windows
 
export PROJ_LIB=$CONDA_PREFIX/share/proj  # Linux and OS X
```

The env var `CONDA_PREFIX` should be set on the base/root env.

_Originally posted by @ocefpaf in https://github.com/conda-forge/basemap-feedstock/issues/30#issuecomment-422504954_

**Comment by jamessong** [comment]
This doesn't work. I still get the error under spyder

from mpl_toolkits.basemap import Basemap 
Traceback (most recent call last):

  File "<ipython-input-1-c18d700c1d76>", line 1, in <module>
    from mpl_toolkits.basemap import Basemap

  File "C:\ProgramData\Anaconda3\lib\site-packages\mpl_toolkits\basemap\__init__.py", line 146, in <module>
    pyproj_datadir = os.environ['PROJ_LIB']

  File "C:\ProgramData\Anaconda3\lib\os.py", line 678, in __getitem__
    raise KeyError(key) from None

KeyError: 'PROJ_LIB'

**Comment by ocefpaf** [comment]
> This doesn't work. I still get the error under spyder

Please report that to the `spyder` group. I have no idea who env variables are dealt with in spyder.
