### ISSUE TITLE
KeyError 'PROJ_LIB' in Python 3.7

### ISSUE THREAD

**Issue by max-jan** [conda-forge/basemap-feedstock#47]
Issue: KeyError 'PROJ_LIB' in Python 3.7

<br/>
Environment (<code>conda list</code>):
<details>

```
$ proj4 6.0

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

If an error such as "KeyError PROJ_LIB" occurs when
from mpl_toolkits.basemap import Basemap

solution: 
downgrade proj4 . like this----------------

conda install -c conda-forge proj4=5.2

**Comment by ocefpaf** [comment]
We would need more details to actually debug this. I don't see who you ended up with `proj4 6` b/c `conda-forge`'s basemap is pinned to `5.2.0`.
