### ISSUE TITLE
KeyError: PROJ_LIB

### ISSUE THREAD

**Issue by pythonweather** [conda-forge/basemap-feedstock#52]
I know this issue has been mentioned several times as I have extensively searched for resolutions. I have followed along every single thread and basically it's transitioned into nothing but clicking different links, opening new tabs (( have about a dozen different tabs open), and getting nowhere. Essentially, it's like calling a help center and being re-directed 20 different times and ending back at square one. I will explain everything in as much detail as possible in hopes of finding a resolution.

1. Using the `from mpl_toolkits.basemap import Basemap` I am trying to import Basemap
2. I have python 3.7 and I have made sure versions of everything needed (such as proj4) are up-to-date. 
3. My operating platform is Windows 10.
4. I am using Spyder obtained through downloading Anaconda

I am trying to follow along instructions on the following link to generate an output of what is shown at the very bottom of the document (page 3)

https://arset.gsfc.nasa.gov/sites/default/files/airquality/webinars/18-hires/Python%20Instructions.pdf

I've downloaded the test_python.py document, opened it within Spyder, and ran it. When I run it I obtain an error which states its within line 678 and the error is KeyWordErro: 'PROJ_LIB'.

I've read stuff involving environment variables and setting something but I am just learning python and I guess I am working on something that is certainly above my knowledge level...it's like attempting to run a marathon before you even learned how to walk. 

Here is a snip-it of the error message. I have zero clue what to do and like I've said, I've clicked on dozens of different links trying to follow along with what I've read.

I've also done the create TEST method, activating the TEST, and doing `python -c "from mpl_toolkits.basemap import Basemap" and when I run it nothing happens. 

![image](https://user-images.githubusercontent.com/53944473/62949251-dca35c80-bdb3-11e9-984a-821313d0ae5d.png)

**Comment by ocefpaf** [comment]
> I am using Spyder obtained through downloading Anaconda

This may be the reason. However, we cannot debug your issue b/c you did not filled the required information when you opened it. Please carefully read the required information, shown to you when you open an issue.
