### ISSUE TITLE
basemap not working on Windows

### ISSUE THREAD

**Issue by dstrozzi** [conda-forge/basemap-feedstock#62]
Issue:
I cannot import basemap on Windows, due to problem with epsg.  This is referenced in some prior closed issues, such at https://github.com/conda-forge/basemap-feedstock/issues/45 and ones referenced there.  A few days ago I ran "conda update conda" and "conda update --all" so I should be up to date on everything.

>>> from mpl_toolkits.basemap import Basemap
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\strozzi2\AppData\Local\Continuum\anaconda3\lib\site-packages\mpl_toolkits\basemap\__init__.py", line 156, in <module>
    epsgf = open(os.path.join(pyproj_datadir,'epsg'))
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\strozzi2\\AppData\\Local\\Continuum\\anaconda3\\Library\\share\\proj\\epsg'
>>>

Environment
<code>

(base) Z:\AppData\Local\Continuum\anaconda3\pkgs>conda list
# packages in environment at C:\Users\strozzi2\AppData\Local\Continuum\anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0                    py37_0
alabaster                 0.7.12                   py37_0
anaconda-client           1.7.2                    py37_0
anaconda-navigator        1.9.12                   py37_0
argh                      0.26.2                   py37_0
astroid                   2.3.3                    py37_0
async                     0.0                      pypi_0    pypi
atomic                    0.0                      pypi_0    pypi
atomicwrites              1.4.0                      py_0
attrs                     19.3.0                     py_0
autopep8                  1.4.4                      py_0
babel                     2.8.0                      py_0
backcall                  0.2.0                      py_0
backports                 1.0                        py_2
backports.functools_lru_cache 1.6.1                      py_0
backports.tempfile        1.0                        py_1
backports.weakref         1.0.post1                  py_1
basemap                   1.2.0            py37h4e5d7af_0
bcrypt                    3.1.7            py37he774522_1
beautifulsoup4            4.9.1                    py37_0
blas                      1.0                         mkl
bleach                    3.1.5                      py_0
brotlipy                  0.7.0           py37he774522_1000
bswiz                     0.0                      pypi_0    pypi
bzip2                     1.0.8                he774522_0
ca-certificates           2020.6.24                     0
certifi                   2020.6.20                py37_0
cffi                      1.14.0           py37h7a1dbc1_0
cftime                    1.1.2            py37h2a96729_0
chardet                   3.0.4                 py37_1003
click                     7.1.2                      py_0
cloudpickle               1.5.0                      py_0
clyent                    1.2.2                    py37_1
colorama                  0.4.3                      py_0
colorcet                  2.0.1                    pypi_0    pypi
coloring                  0.0                      pypi_0    pypi
conda                     4.8.3                    py37_0
conda-build               3.18.11                  py37_0
conda-env                 2.6.0                         1
conda-package-handling    1.6.1            py37h62dcd97_0
conda-verify              3.4.2                      py_1
cryptography              2.9.2            py37h7a1dbc1_0
curl                      7.71.0               h2a8f88b_0
cycler                    0.10.0                   py37_0
decorator                 4.4.2                      py_0
defusedxml                0.6.0                      py_0
diff-match-patch          20181111                   py_0
dnd                       0.0                      pypi_0    pypi
docutils                  0.16                     py37_1
entrypoints               0.3                      py37_0
fds-database              0.0.1                    pypi_0    pypi
filelock                  3.0.12                     py_0
flake8                    3.7.9                    py37_0
freetype                  2.10.2               hd328e21_0
future                    0.18.2                   py37_1
geos                      3.6.2                h9ef7328_2
glob2                     0.7                        py_0
h2                        0.0                      pypi_0    pypi
h5py                      2.10.0           py37h5e291fa_0
hdf4                      4.2.13               h712560f_2
hdf5                      1.10.4               h7ebc959_0
icc_rt                    2019.0.0             h0cc432a_1
icu                       58.2                 ha925a31_3
idesign                   0.0                      pypi_0    pypi
idna                      2.10                       py_0
imagesize                 1.2.0                      py_0
importlib-metadata        1.7.0                    py37_0
importlib_metadata        1.7.0                         0
intel-openmp              2020.1                      216
intervaltree              3.0.2                      py_0
ipykernel                 5.3.0            py37h5ca1d4c_0
ipython                   7.16.1           py37h5ca1d4c_0
ipython_genutils          0.2.0                    py37_0
ipywidgets                7.5.1                      py_0
isort                     4.3.21                   py37_0
jedi                      0.15.2                   py37_0
jinja2                    2.11.2                     py_0
jpeg                      9b                   hb83a4c4_2
json5                     0.9.5                      py_0
jsonschema                3.2.0                    py37_0
jupyter_client            6.1.5                      py_0
jupyter_core              4.6.3                    py37_0
jupyterlab                2.1.5                      py_0
jupyterlab_server         1.2.0                      py_0
keyring                   21.2.1                   py37_0
kiwisolver                1.2.0            py37h74a9793_0
krb5                      1.18.2               hc04afaa_0
laser                     0.0                      pypi_0    pypi
lazy-object-proxy         1.5.0            py37he774522_0
libarchive                3.4.2                h5e25573_0
libcurl                   7.71.0               h2a8f88b_0
libiconv                  1.15                 h1df5818_7
liblief                   0.10.1               ha925a31_0
libllvm9                  9.0.1                h21ff451_0
libnetcdf                 4.7.3                h1302dcc_0
libpng                    1.6.37               h2a8f88b_0
libsodium                 1.0.18               h62dcd97_0
libspatialindex           1.9.3                h33f27b4_0
libssh2                   1.9.0                h7a1dbc1_1
libtiff                   4.1.0                h56a325e_1
libxml2                   2.9.10               h464c3ec_1
llvmlite                  0.33.0           py37ha925a31_0
lz4-c                     1.9.2                h62dcd97_0
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
markupsafe                1.1.1            py37he774522_0
matplotlib                3.2.2                         0
matplotlib-base           3.2.2            py37h64f37c6_0
mccabe                    0.6.1                    py37_1
menuinst                  1.4.16           py37he774522_1
mistune                   0.8.4            py37he774522_0
mkl                       2020.1                      216
mkl-service               2.3.0            py37hb782905_0
mkl_fft                   1.1.0            py37h45dec08_0
mkl_random                1.1.1            py37h47e9c7a_0
mock                      3.0.5                    pypi_0    pypi
msys2-conda-epoch         20160418                      1
navigator-updater         0.2.1                    py37_0
nbconvert                 5.6.1                    py37_0
nbformat                  5.0.7                      py_0
netcdf4                   1.5.3            py37h012c1a0_0
nifarch                   0.0                      pypi_0    pypi
nifcpps                   0.0                      pypi_0    pypi
nifdata                   0.0                      pypi_0    pypi
nifdb                     1.0                      pypi_0    pypi
nifshots                  0.0                      pypi_0    pypi
notebook                  6.0.3                    py37_0
npminus                   0.0                      pypi_0    pypi
npplus                    0.9.8                    pypi_0    pypi
nspectra                  0.0                      pypi_0    pypi
numba                     0.50.1           py37h47e9c7a_0
numpy                     1.18.5           py37h6530119_0
numpy-base                1.18.5           py37hc3f5095_0
numpydoc                  1.1.0                      py_0
olefile                   0.46                     py37_0
openssl                   1.1.1g               he774522_0
packaging                 20.4                       py_0
pandoc                    2.9.2.1                       0
pandocfilters             1.4.2                    py37_1
paramiko                  2.7.1                      py_0
parso                     0.5.2                      py_0
pathtools                 0.1.2                      py_1
pbr                       5.2.1                    pypi_0    pypi
periodictable             1.5.2                    pypi_0    pypi
pexpect                   4.8.0                    py37_0
picklejar                 0.0                      pypi_0    pypi
pickleshare               0.7.5                    py37_0
pillow                    7.2.0            py37hcc1f983_0
pip                       20.1.1                   py37_1
pkginfo                   1.5.0.1                  py37_0
pluggy                    0.13.1                   py37_0
proj                      7.0.1                hf5a9257_1
prometheus_client         0.8.0                      py_0
prompt-toolkit            3.0.5                      py_0
psutil                    5.7.0            py37he774522_0
py-lief                   0.10.1           py37ha925a31_0
pycodestyle               2.5.0                    py37_0
pycosat                   0.6.3            py37he774522_0
pycparser                 2.20                       py_0
pydocstyle                5.0.2                      py_0
pydoe                     0.3.8                    pypi_0    pypi
pyfds                     0.0.1.dev1               pypi_0    pypi
pyflakes                  2.1.1                    py37_0
pygments                  2.6.1                      py_0
pylint                    2.4.4                    py37_0
pynacl                    1.4.0            py37h62dcd97_0
pyopenssl                 19.1.0                   py37_0
pyorick                   1.4                      pypi_0    pypi
pyparsing                 2.4.7                      py_0
pyproj                    2.6.1.post1      py37ha1e340d_1
pyqt                      5.9.2            py37h6538335_2
pyreadline                2.1                      py37_1
pyrsistent                0.16.0           py37he774522_0
pyshp                     2.1.0                      py_0
pysocks                   1.7.1                    py37_0
python                    3.7.7                h81c818b_4
python-dateutil           2.8.1                      py_0
python-jsonrpc-server     0.3.4                      py_0
python-language-server    0.31.10                  py37_0
python-libarchive-c       2.9                        py_0
pytz                      2020.1                     py_0
pywin32                   227              py37he774522_1
pywin32-ctypes            0.2.0                 py37_1000
pywinpty                  0.5.7                    py37_0
pyyaml                    5.3.1            py37he774522_1
pyzmq                     19.0.1           py37ha925a31_1
qdarkstyle                2.8.1                      py_0
qnd                       0.0                      pypi_0    pypi
qt                        5.9.7            vc14h73c81de_0
qtawesome                 0.7.2                      py_0
qtconsole                 4.7.5                      py_0
qtpy                      1.9.0                      py_0
requests                  2.24.0                     py_0
rope                      0.17.0                     py_0
rtree                     0.9.4            py37h21ff451_1
ruamel_yaml               0.15.87          py37he774522_1
scipy                     1.5.0            py37h9439919_0
send2trash                1.5.0                    py37_0
setuptools                47.3.1                   py37_0
sip                       4.19.8           py37h6538335_0
six                       1.15.0                     py_0
snowballstemmer           2.0.0                      py_0
sortedcontainers          2.2.2                      py_0
soupsieve                 2.0.1                      py_0
sphinx                    3.1.2                      py_0
sphinx-rtd-theme          0.4.3                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.2                      py_0
sphinxcontrib-devhelp     1.0.2                      py_0
sphinxcontrib-htmlhelp    1.0.3                      py_0
sphinxcontrib-jsmath      1.0.1                      py_0
sphinxcontrib-qthelp      1.0.3                      py_0
sphinxcontrib-serializinghtml 1.1.4                      py_0
spyder                    4.1.3                    py37_0
spyder-kernels            1.9.1                    py37_0
sqlite                    3.32.3               h2a8f88b_0
tbb                       2020.0               h74a9793_0
terminado                 0.8.3                    py37_0
testpath                  0.4.4                      py_0
tk                        8.6.10               he774522_0
tornado                   6.0.4            py37he774522_1
tqdm                      4.47.0                     py_0
traitlets                 4.3.3                    py37_0
ujson                     1.35             py37hfa6e2cd_0
urllib3                   1.25.9                     py_0
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_3
watchdog                  0.10.3                   py37_0
wcwidth                   0.2.5                      py_0
webencodings              0.5.1                    py37_1
wheel                     0.34.2                   py37_0
widgetsnbextension        3.5.1                    py37_0
win_inet_pton             1.1.0                    py37_0
wincertstore              0.2                      py37_0
winpty                    0.4.3                         4
wrapt                     1.12.1           py37he774522_1
xlrd                      1.2.0                    py37_0
xmltodict                 0.12.0                     py_0
xz                        5.2.5                h62dcd97_0
yaml                      0.2.5                he774522_0
yapf                      0.30.0                     py_0
ylmtools                  0.0                      pypi_0    pypi
zeromq                    4.3.2                ha925a31_2
zipp                      3.1.0                      py_0
zlib                      1.2.11               h62dcd97_4
zstd                      1.4.4                ha9fde0e_3

</code>

Details about  <code>conda</code> and system
<code>
(base) Z:\AppData\Local\Continuum\anaconda3\pkgs>conda info

     active environment : base
    active env location : C:\Users\strozzi2\AppData\Local\Continuum\anaconda3
            shell level : 1
       user config file : z:\.condarc
 populated config files : z:\.condarc
          conda version : 4.8.3
    conda-build version : 3.18.11
         python version : 3.7.7.final.0
       virtual packages :
       base environment : C:\Users\strozzi2\AppData\Local\Continuum\anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\strozzi2\AppData\Local\Continuum\anaconda3\pkgs
                          z:\.conda\pkgs
                          C:\Users\strozzi2\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\strozzi2\AppData\Local\Continuum\anaconda3\envs
                          z:\.conda\envs
                          C:\Users\strozzi2\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.3 requests/2.24.0 CPython/3.7.7 Windows/10 Windows/10.0.17763
          administrator : False
             netrc file : None
           offline mode : False

**Comment by ocefpaf** [comment]
It is hard to read your `.condarc` and `conda list` but it does not look like you are using conda-forge's package.

Please read https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge and follow the instructions there.

**Comment by dstrozzi** [comment]
OK thanks, I will get onto conda forge later today

**Comment by ocefpaf** [comment]
Closing this then b/c it is a problem with the package in defaults.
